[package]
name = "purgedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
eframe = { version = "0.24.1", features = ["persistence"] }
egui = "0.24.1"
egui_extras = "0.24.2"
env_logger = "0.10.1"
fuzzy-matcher = "0.3.7"
hex_color = "3.0.0"
rand = "0.8.5"
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde = { version = "1.0.193", features = ["derive"] }

